### PR TITLE
First Contribution

### PR DESCRIPTION
**Pull request by AnishereMariam**
Added two visualizations using the Bokeh Libraries

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @anisheremariam  thanks for the PR, this satisfies the micro task. You have demonstrated familiarity with the Bokeh and PandasAPIS. I appreciate the legend on the second plot My main comment would be that the notebooks and plots could use more "story", e.g.   the notebooks could benefit from some narrative markdown text explaining what is to be looked at, why it is interesting, any conclusions the plots supports, etc. 

cc @pavithraes for additional comments

**Comment by AnishereMariam** [comment]
@bryevdv, thank you so much. Your comment and observations are duly noted. I have created a blog series that includes the detailed explanation of each visualization. View my blog post [HERE](https://anisheremariam.github.io/Bokeh_Outreachy/). 

cc @pavithraes

**Comment by pavithraes** [comment]
@anisheremariam I think your issue #21 (which includes your blog + gist with more plots) supersedes your work in this PR. If you agree, please feel free to close this PR and we can keep discussions on #21. :)

**Comment by AnishereMariam** [comment]
@pavithraes, yes I totally agree with you. #21 is the parent of my contributions. I will close this now as suggested. Thank you.

**Pull request closed without merging**
